[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/main"
