[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@9", "pnpm install --frozen-lockfile=false"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/main"
